// flow-typed signature: 74dfec99bf69c2be663daab1449c453a
// flow-typed version: <<STUB>>/react-portal-tooltip_v^2.4.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-portal-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-portal-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-portal-tooltip/lib/index' {
  declare module.exports: any;
}

declare module 'react-portal-tooltip/src/index' {
  declare module.exports: any;
}

declare module 'react-portal-tooltip/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-portal-tooltip/lib/index.js' {
  declare module.exports: $Exports<'react-portal-tooltip/lib/index'>;
}
declare module 'react-portal-tooltip/src/index.js' {
  declare module.exports: $Exports<'react-portal-tooltip/src/index'>;
}
declare module 'react-portal-tooltip/test/index.js' {
  declare module.exports: $Exports<'react-portal-tooltip/test/index'>;
}
