import type { UnitCircleItem } from './types'

export const CIRCLE_DEGREES = 360

export const unitCircle: UnitCircleItem[] = [
	{ degree: 0, radian: { numerator: 0, denominator: 1 } },
	{ degree: 30, radian: { numerator: 1, denominator: 6 } },
	{ degree: 45, radian: { numerator: 1, denominator: 4 } },
	{ degree: 60, radian: { numerator: 1, denominator: 3 } },
	{ degree: 90, radian: { numerator: 1, denominator: 2 } },
	{ degree: 120, radian: { numerator: 2, denominator: 3 } },
	{ degree: 135, radian: { numerator: 3, denominator: 4 } },
	{ degree: 150, radian: { numerator: 5, denominator: 6 } },
	{ degree: 180, radian: { numerator: 1, denominator: 1 } },
	{ degree: 210, radian: { numerator: 7, denominator: 6 } },
	{ degree: 225, radian: { numerator: 5, denominator: 4 } },
	{ degree: 240, radian: { numerator: 4, denominator: 3 } },
	{ degree: 270, radian: { numerator: 3, denominator: 2 } },
	{ degree: 300, radian: { numerator: 5, denominator: 3 } },
	{ degree: 315, radian: { numerator: 7, denominator: 4 } },
	{ degree: 330, radian: { numerator: 11, denominator: 6 } },
	{ degree: 360, radian: { numerator: 2, denominator: 1 } },
]

export const specificCircle: UnitCircleItem[] = [
	{ degree: 0, radian: { numerator: 0, denominator: 1 } },
	{ degree: 15, radian: { numerator: 1, denominator: 12 } },
	{ degree: 30, radian: { numerator: 1, denominator: 6 } },
	{ degree: 45, radian: { numerator: 1, denominator: 4 } },
	{ degree: 60, radian: { numerator: 1, denominator: 3 } },
	{ degree: 75, radian: { numerator: 5, denominator: 12 } },
	{ degree: 90, radian: { numerator: 1, denominator: 2 } },
	{ degree: 105, radian: { numerator: 7, denominator: 12 } },
	{ degree: 120, radian: { numerator: 2, denominator: 3 } },
	{ degree: 135, radian: { numerator: 3, denominator: 4 } },
	{ degree: 150, radian: { numerator: 5, denominator: 6 } },
	{ degree: 165, radian: { numerator: 11, denominator: 12 } },
	{ degree: 180, radian: { numerator: 1, denominator: 1 } },
	{ degree: 75, radian: { numerator: 5, denominator: 12 } },
	{ degree: 195, radian: { numerator: 13, denominator: 12 } },
	{ degree: 210, radian: { numerator: 7, denominator: 6 } },
	{ degree: 225, radian: { numerator: 5, denominator: 4 } },
	{ degree: 240, radian: { numerator: 4, denominator: 3 } },
	{ degree: 255, radian: { numerator: 17, denominator: 12 } },
	{ degree: 270, radian: { numerator: 3, denominator: 2 } },
	{ degree: 285, radian: { numerator: 19, denominator: 12 } },
	{ degree: 300, radian: { numerator: 5, denominator: 3 } },
	{ degree: 315, radian: { numerator: 7, denominator: 4 } },
	{ degree: 330, radian: { numerator: 11, denominator: 6 } },
	{ degree: 345, radian: { numerator: 23, denominator: 12 } },
	{ degree: 360, radian: { numerator: 2, denominator: 1 } },
]
